version: '3.8'
services:
  whatever_the_weather:
    image: whatever_the_weather:latest
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    volumes:
      - .:/app